package org.stanford.ncbo.owlapi.wrapper;

public enum ParserError {
	OUPUT_REPO_MISSING, INPUT_REPO_MISSING, OUPUT_REPO_NOT_A_FOLDER, 
	INPUT_REPO_NOT_A_FOLDER, OUPUT_REPO_CANNOT_BE_CREATED,
	OWL_PARSE_EXCEPTION, OWL_FILE_NOT_REMOVED_FROM_QUUE, 
	OWL_CREATE_ONTOLOGY_EXCEPTION, MASTER_FILE_MISSING,
	OWL_STORAGE_EXCEPTION, UNKNOWN,MASTER_FILE_IS_FOLDER, OWL_IMPORT_MISSING
}
